spring:
  datasource:
    url: jdbc:mysql://localhost/readinglist
    username: dbuser
    password: dbpass
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
  redis:
    database: 0 #数据库索引
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8  #最大连接数
        max-wait: -1  #最大阻塞等待时间(负数表示没限制)
        max-idle: 8   #最大空闲
        min-idle: 0  #最小空闲
    timeout: 10000  #连接超时时间
    
    
amazon:
  associateId: habuma-20

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.mapper
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      
info:
  contact:
    email: chenxiange@houbank.com
    phone: 1554079966
    